image: "python:3.8"

before_script:
  - pip install -r requirements.txt
  - mysql -u root -e "create user 'Trevor'@'localhost' identified by 'password';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON * . * TO 'Trevor'@'localhost';"

pytest:
  script:
    - pytest -v
